live_config_reload = true

[[colors.indexed_colors]]
color = "0xdfaf8f"
index = 16

[[colors.indexed_colors]]
color = "0x000000"
index = 17

[[colors.indexed_colors]]
color = "0x404040"
index = 18

[[colors.indexed_colors]]
color = "0x606060"
index = 19

[[colors.indexed_colors]]
color = "0x808080"
index = 20

[[colors.indexed_colors]]
color = "0xc0c0c0"
index = 21

[colors.bright]
black = "0x6f6f6f"
blue = "0x7cb8bb"
cyan = "0x93e0e3"
green = "0x5f7f5f"
magenta = "0xdc8cc3"
red = "0xdca3a3"
white = "0xffffff"
yellow = "0xe0cf9f"

[colors.cursor]
cursor = "0xdcdccc"
text = "0x383838"

[colors.normal]
black = "0x383838"
blue = "0x7cb8bb"
cyan = "0x93e0e3"
green = "0x5f7f5f"
magenta = "0xdc8cc3"
red = "0xdca3a3"
white = "0xdcdccc"
yellow = "0xe0cf9f"

[colors.primary]
background = "0x3f3f3f"
foreground = "0xdcdccc"

[font]
size = 9.0

[font.normal]
family = "monospace"

[font.offset]
x = 0
y = 0

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window.padding]
x = 2
y = 2
