#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

xrdb .Xresources
xset r rate 300 30
xinput set-prop "SynPS/2 Synaptics TouchPad" "Synaptics Finger" 40 50 0
xinput set-prop "SynPS/2 Synaptics TouchPad" "Synaptics Noise Cancellation" 32 32
redshift -l 40:-88 -t 6500:3800 &
xsetroot -solid darkslategrey
dropboxd&
start-pulseaudio-x11
xset b 100
xmonad
