#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

xrdb .Xresources
xset b 100 880 50
xset r rate 300 30
redshift -l 40:-88 -t 6500:3800 &
xsetroot -solid darkslategrey
dropboxd&
xmonad
