#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

xrdb .Xresources
xset r rate 300 30
xautolock -time 15 -locker 'keepass --lock-all' &
xinput set-prop 'Logitech Unifying Device. Wireless PID:101b' 'Device Accel Profile' 2
xinput set-prop 'Logitech Unifying Device. Wireless PID:101b' 'Device Accel Constant Deceleration' 2
xinput set-prop 'Logitech Unifying Device. Wireless PID:101b' 'Device Accel Adaptive Deceleration' 2
xinput set-prop 'Logitech Unifying Device. Wireless PID:101b' 'Device Accel Velocity Scaling' 2
xinput set-prop 'Logitech M705' 'Device Accel Profile' 2
xinput set-prop 'Logitech M705' 'Device Accel Constant Deceleration' 2
xinput set-prop 'Logitech M705' 'Device Accel Adaptive Deceleration' 2
xinput set-prop 'Logitech M705' 'Device Accel Velocity Scaling' 2
#xrandr --output DVI-D-1 --auto --output VGA-1 --auto --left-of DVI-D-1
#xrandr --output LVDS-0 --off
#xrandr --output DVI-D-0 --auto --output VGA-0 --auto --left-of DVI-D-0
redshift -l 40:-88 -t 6500:3800 &
export VDPAU_NVIDIA_NO_OVERLAY=1
#compton --backend glx --glx-no-stencil --glx-no-rebind-pixmap --vsync=opengl-swc --paint-on-overlay --glx-swap-method=2 &
hsetroot -solid '#2f4f4f'
dropbox&
start-pulseaudio-x11
xset b 100
xmonad
