#!/usr/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

xrdb .Xresources
synclient RTCornerButton=2
xset r rate 300 35
xset b 100 880 50
redshift -l 40:-88 -t 6500:3000 &
export VDPAU_NVIDIA_NO_OVERLAY=1
compton&
#xsetroot -solid darkslategrey
hsetroot -solid '#2f4f4f'
dropboxd&
#exec openbox-session
xmonad
